# H
spring.datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
  username: sa
  password: sa

# Actuator - production ready endpoint config. runs in 9000 port - different from app itself 
management:
  server.port: 9000
  endpoints.web:
    enabled: true
    expose: "*"
    base-path: /manage
  health.defaults.enabled: false

# Redis
spring.redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
 
# Swagger 
springfox.documentation:
  swagger.v2.path: /swagger
  
---
spring.profiles: prod

# MySQL for prod profile
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pricingdb?useSSL=false
    username: ${JDBC_USER_NAME:root}
    password: ${JDBC_PASSWORD:root1234}
  jpa:
    hibernate:
      ddl-auto: ${DB_MODE:create}

